apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansichtkaarten-deployment
  labels:
    app: ansichtkaarten-deployment
    keel.sh/policy: force
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansichtkaarten-deployment
  template:
    metadata:
      labels:
        app: ansichtkaarten-deployment
    spec:
      containers:
      - name: ansichtkaarten-deployment
        image: registry.voidcorp.nl/library/ansichtkaarten:master
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ansichtkaarten-deployment-service
spec:
  selector:
    app: ansichtkaarten-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ansichtkaarten-deployment-ingress
spec:
  rules:
  - host: "groenehartansichtkaarten.nl"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: ansichtkaarten-deployment-service
            port: 
              number: 80

